# Generated by Django 5.1.6 on 2025-03-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userfollowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowers',
            new_name='UserFollower',
        ),
    ]
